# baseURL = "https://main.dj1h7qwffogh3.amplifyapp.com/"
languageCode = "en-us"
title = "Hugo-Amplify Test"
#theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "Seán Murphy"
    description = "A simple demo site"
    #githubUsername = "#"
    accent = "light-blue"
    showBorder = true
    backgroundColor = "grey"
    font = "Roboto Mono"
    #font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "dark"
    highlightLanguages = ["go", "yaml", "bash"]
    copyright = "© Seán Murphy, 2021. Powered by [Hugo](https://gohugo.io) and the Minimal theme. GDPR Compliant; no tracking enabled."
    version = "0.0.2"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:info@example.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/seanrmurphy/hugu-amplify-test"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/seanrmurphy/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/seanrmurphy1"
    name = "fab fa-linkedin"
    weight = 4

[module]
  [[module.imports]]
    path = "github.com/calintat/minimal"

  [[module.imports]]
    path = "github.com/theNewDynamic/hugo-module-tnd-forms"

# GDPR related
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

